#!/usr/bin/env python3
# /// script
# requires-python = ">=3.10"
# dependencies = [
#     "pyyaml",
# ]
# ///
import argparse
import re
from pathlib import Path

import yaml


DEFAULT_SOURCE = Path("scripts/data/credits.yaml")
DEFAULT_ASM = Path("asm/credits.asm")

STRING_START = "// BEGIN GENERATED NEW CREDIT STRINGS"
STRING_END = "// END GENERATED NEW CREDIT STRINGS"
BLOCK_START = "// BEGIN GENERATED NEW CREDITS"
BLOCK_END = "// END GENERATED NEW CREDITS"


def parse_credits(path):
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError(f"{path}: expected a mapping")
    if not isinstance(data.get("header"), str):
        raise ValueError(f"{path}: header must be a string")
    if not isinstance(data.get("video"), int):
        raise ValueError(f"{path}: video must be an integer")
    if not isinstance(data.get("pages"), list):
        raise ValueError(f"{path}: pages must be a list")
    for index, page in enumerate(data["pages"], 1):
        if not isinstance(page, dict):
            raise ValueError(f"{path}: page {index} must be a mapping")
        if not isinstance(page.get("title"), str):
            raise ValueError(f"{path}: page {index} title must be a string")
        names = page.get("names", [])
        if not isinstance(names, list) or not all(isinstance(name, str) for name in names):
            raise ValueError(f"{path}: page {index} names must be a list of strings")
        clear = page.get("clear_names", {})
        if not isinstance(clear, dict):
            raise ValueError(f"{path}: page {index} clear_names must be a mapping")
    return data


def asm_num(value):
    if isinstance(value, str):
        return value
    if value == 0:
        return str(value)
    return hex(value)


def asm_string(value):
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def slugify(text):
    text = re.sub(r"<[^>]*>", "", text)
    text = text.lower()
    text = re.sub(r"[^a-z0-9]+", "_", text)
    text = text.strip("_")
    return text or "credit_string"


def collect_labels(data):
    labels_by_text = {}
    labels_in_use = set()
    ordered_text = []

    def add(text):
        if text in labels_by_text:
            return
        base = slugify(text)
        label = base
        suffix = 2
        while label in labels_in_use:
            label = f"{base}_{suffix}"
            suffix += 1
        labels_by_text[text] = label
        labels_in_use.add(label)
        ordered_text.append(text)

    add(data["header"])
    for page in data["pages"]:
        add(page["title"])
        for name in page.get("names", []):
            add(name)

    return labels_by_text, ordered_text


def emit_command(lines, values):
    for i, value in enumerate(values):
        directive = ".word" if i == 2 and value == 0xFFFFFFFF else ".dw"
        lines.append(f"{directive} {asm_num(value)}")
    lines.append("")


def emit_draw(lines, x, y, label):
    emit_command(lines, [x, y, 0x2, 0x8, 0x18, label])


def generate_strings(data):
    labels_by_text, ordered_text = collect_labels(data)
    lines = [
        STRING_START,
        "// Generated by scripts/tasks/generate_credits.py from scripts/data/credits.yaml.",
    ]
    for text in ordered_text:
        lines.extend([f"{labels_by_text[text]}:", f".string {asm_string(text)}"])
    lines.append(STRING_END)
    return "\n".join(lines) + "\n\n", labels_by_text


def generate_block(data, labels_by_text):
    lines = [
        BLOCK_START,
        "// Generated by scripts/tasks/generate_credits.py from scripts/data/credits.yaml.",
        "",
    ]
    emit_command(lines, [0, 0, 1, data["video"], 0, "null"])
    emit_draw(lines, 0x30, 0x60, labels_by_text[data["header"]])

    for page in data["pages"]:
        names = page.get("names", [])
        emit_draw(lines, 0x30, 0x90, labels_by_text[page["title"]])
        for index, name in enumerate(names):
            emit_draw(lines, 0x90, 0xA8 + (index * 0x18), labels_by_text[name])

        emit_command(lines, [0, 0, 0x3, 0x96, 0, "null"])

        clear = page.get("clear_names", {})
        start = clear.get("start", 1)
        count = clear.get("count", len(names) + 1)
        x = clear.get("x", 0x30)
        emit_command(lines, [start, count, 0x6, x, 0x18, "null"])

    lines.append("// End")
    emit_command(lines, [0, 0, 0xFFFFFFFF, 0, 0, "null"])
    lines.append(".dw null")
    lines.append("")
    lines.append(BLOCK_END)
    return "\n".join(lines) + "\n\n"


def replace_between(text, start_marker, end_marker, replacement):
    if start_marker in text and end_marker in text:
        pattern = re.compile(
            re.escape(start_marker) + r".*?" + re.escape(end_marker) + r"\n*",
            re.DOTALL,
        )
        return pattern.sub(replacement, text, count=1)
    return None


def replace_legacy_string_region(text, replacement):
    pattern = re.compile(
        r"(null:\n\.byte 0x0\n\n)(.*?)(\.align 0x10\n)",
        re.DOTALL,
    )
    match = pattern.search(text)
    if not match:
        raise ValueError("could not find legacy new credit string region")
    return pattern.sub(r"\1" + replacement + r"\3", text, count=1)


def replace_legacy_block_region(text, replacement):
    pattern = re.compile(
        r"//\n// Newly-added credits\n//\n\n.*?(?=\ned0_pss:)",
        re.DOTALL,
    )
    if not pattern.search(text):
        raise ValueError("could not find legacy newly-added credits block")
    return pattern.sub("//\n// Newly-added credits\n//\n\n" + replacement, text, count=1)


def update_asm(asm_path, string_region, block_region):
    text = asm_path.read_text(encoding="utf-8")

    replaced = replace_between(text, STRING_START, STRING_END, string_region)
    text = replaced if replaced is not None else replace_legacy_string_region(text, string_region)

    replaced = replace_between(text, BLOCK_START, BLOCK_END, block_region)
    text = replaced if replaced is not None else replace_legacy_block_region(text, block_region)

    asm_path.write_text(text, encoding="utf-8")


def generate_credits(source=DEFAULT_SOURCE, asm=DEFAULT_ASM, check=False):
    data = parse_credits(source)
    string_region, labels_by_text = generate_strings(data)
    block_region = generate_block(data, labels_by_text)

    before = asm.read_text(encoding="utf-8")
    update_asm(asm, string_region, block_region)
    after = asm.read_text(encoding="utf-8")

    if check and before != after:
        asm.write_text(before, encoding="utf-8")
        raise SystemExit(f"{asm} is stale; run scripts/tasks/generate_credits.py")


def main():
    parser = argparse.ArgumentParser(description="Generate the new credits in asm/credits.asm")
    parser.add_argument("--source", type=Path, default=DEFAULT_SOURCE)
    parser.add_argument("--asm", type=Path, default=DEFAULT_ASM)
    parser.add_argument("--check", action="store_true", help="fail if asm output is stale")
    args = parser.parse_args()

    generate_credits(args.source, args.asm, args.check)


if __name__ == "__main__":
    main()
